# Change these first
owner: sid-r-singh # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: sidrana.dev
    url: https://sidrana.dev
    maxResponseTime: 1000
  - name: Multimedia BRN
    url: https://mbrn.in/ping.html
    icon: https://mbrn.in/images/icons/favicon-32x32.png
    maxResponseTime: 1500


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: https://status.sid.one/
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Sid status page
  introTitle: "**Sid status page** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This prage tracks the status of my projects in near **real-time** using data from this [GitHub repository](https://github.com/sid-r-singh/status). No server is being used — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
